#ifndef status_h
#define status_h

typedef enum
{
	ETAT_OK = 0,
	ETAT_ERROR = -1,
	ETAT_EPERM = -2,			//Operation not permitted
	ETAT_ENOENT = -3,			//No such file or directory
	ETAT_ESRCH = -4,			//No such process
	ETAT_EINTR = -5,			//Interrupted system call
	ETAT_EIO = -6,				//I/O error
	ETAT_ENXIO = -7,			//No such device or address
	ETAT_E2BIG = -8,			//Argument list too long
	ETAT_ENOEXEC = -9,			//Exec format error
	ETAT_ECHILD = -10,			//No child processes
	ETAT_EAGAIN = -11,			//Try again
	ETAT_ENOMEM = -12,			//Out of memory
	ETAT_EACCES = -13,			//Permission denied
	ETAT_EFAULT = -14,			//Bad address
	ETAT_ENOTBLK = -15,			//Block device required
	ETAT_EBUSY = -16,			//Device or resource busy
	ETAT_EEXIST = -17,			//File exists
	ETAT_EXDEV = -18,			//Cross-device link
	ETAT_ENODEV = -19,			//No such device
	ETAT_ENOTDIR = -20,			//Not a directory
	ETAT_EISDIR = -21,			//Is a directory
	ETAT_EINVAL = -22,			//Invalid argument
	ETAT_ENFILE = -23,			//File table overflow
	ETAT_EMFILE = -24,			//Too many open files
	ETAT_ENOTTY = -25,			//Not a typewriter
	ETAT_ETXTBSY = -26,			//Text file busy
	ETAT_EFBIG = -27,			//File too large
	ETAT_ENOSPC = 28,			//No space left on device
	ETAT_ESPIPE = -29,			//Illegal seek
	ETAT_EROFS = -30,			//Read-only file system
	ETAT_EMLINK = -31,			//Too many links
	ETAT_EPIPE = -32,			//Broken pipe
	ETAT_EDOM = -33,			//Math argument out of domain of func
	ETAT_ERANGE = -34,			//Math result not representable
	ETAT_EDEADLK = -35,			//Resource deadlock would occur
	ETAT_ENAMETOOLONG = -36,	//File name too long
	ETAT_ENOLCK = -37,			//No record locks available
	ETAT_ENOSYS = -38,			//Function not implemented
	ETAT_ENOTEMPTY = -39,		//Directory not empty
	ETAT_ELOOP = -40,			//Too many symbolic links encountered
	ETAT_ENOMSG = -41,			//No message of desired type
	ETAT_EIDRM = -42,			//Identifier removed
	ETAT_ECHRNG = -43,			//Channel number out of range
	ETAT_EL2NSYNC = -44,		//Level 2 not synchronized
	ETAT_EL3HLT = -45,			//Level 3 halted
	ETAT_EL3RST = -46,			//Level 3 reset
	ETAT_ELNRNG = -47,			//Link number out of range
	ETAT_EUNATCH = -48,			//Protocol driver not attached
	ETAT_ENOCSI = -49,			//No CSI structure available
	ETAT_EL2HLT = -50,			//Level 2 halted
	ETAT_EBADE = -51,			//Invalid exchange
	ETAT_EBADR = -52,			//Invalid request descriptor
	ETAT_EXFULL = -53,			//Exchange full
	ETAT_ENOANO = -54,			//No anode
	ETAT_EBADRQC = -55,			//Invalid request code
	ETAT_EBADSLT = -56,			//Invalid slot
	ETAT_EBFONT = 57,			//Bad	 font file format
	ETAT_ENOSTR = -58,			//Dev	ice not a stream
	ETAT_ENODATA = -59,			//No data available
	ETAT_ETIME = -60,			//Timer expired
	ETAT_ENOSR = -61,			//Out of streams resources
	ETAT_ENONET = -62,			//Machine is not on the network
	ETAT_ENOPKG = -63,			//Package not installed
	ETAT_EREMOTE = -64,			//Object is remote
	ETAT_ENOLINK = -65,			//Link has been severed
	ETAT_EADV = -66,			//Advertise error
	ETAT_ESRMNT = -67,			//Srmount error
	ETAT_ECOMM = -68,			//Communication error on send
	ETAT_EPROTO = -69,			//Protocol error
	ETAT_EMULTIHOP = -70,		//Multihop attempted
	ETAT_EDOTDOT = -71,			//RFS specific error
	ETAT_EBADMSG = -72,			//Not a data message
	ETAT_EOVERFLOW = -73,		//Value too large for defined data type
	ETAT_ENOTUNIQ = -74,		//Name not unique on network
	ETAT_EBADFD = -75,			//File descriptor in bad state
	ETAT_EREMCHG = -76,			//Remote address changed
	ETAT_ELIBACC = -77,			//Can not access a needed shared library
	ETAT_ELIBBAD = -78,			//Accessing a corrupted shared library
	ETAT_ELIBSCN = -79,			//.lib section in a.out corrupted
	ETAT_ELIBMAX = -80,			//Attempting to link in too many shared libraries
	ETAT_ELIBEXEC = -81,		//Cannot exec a shared library directly
	ETAT_EILSEQ = -82,			//Illegal byte sequence
	ETAT_ERESTART = -83,		//Interrupted system call should be restarted
	ETAT_ESTRPIPE = -84,		//Streams pipe error
	ETAT_EUSERS = -85,			//Too many users
	ETAT_ENOTSOCK = -86,		//Socket operation on non-socket
	ETAT_EDESTADDRREQ = -87,	//Destination address required
	ETAT_EMSGSIZE = -88,		//Message too long
	ETAT_EPROTOTYPE = -89,		//Protocol wrong type for socket
	ETAT_ENOPROTOOPT = -90,		//Protocol not available
	ETAT_EPROTONOSUPPORT = -91, //Protocol not supported
	ETAT_ESOCKTNOSUPPORT = -92, //Socket type not supported
	ETAT_EOPNOTSUPP = -93,		//Operation not supported on transport endpoint
	ETAT_EPFNOSUPPORT = -94,	//Protocol family not supported
	ETAT_EAFNOSUPPORT = -95,	//Address family not supported by protocol
	ETAT_EADDRINUSE = -96,		//Address already in use
	ETAT_EADDRNOTAVAIL = -97,			//Cannot assign requested address
	ETAT_ENETDOWN = -98,				//Network is down
	ETAT_ENETUNREACH = -99,			//Network is unreachable
	ETAT_ENETRESET = -100,				//Network dropped connection because of reset
	ETAT_ECONNABORTED = -101,			//Software caused connection abort
	ETAT_ECONNRESET = -102,			//Connection reset by peer
	ETAT_ENOBUFS = -103,				//No buffer space available
	ETAT_EISCONN = -104,				//Transport endpoint is already connected
	ETAT_ENOTCONN = -105,				//Transport endpoint is not connected
	ETAT_ESHUTDOWN = -106,				//Cannot send after transport endpoint shutdown
	ETAT_ETOOMANYREFS = -107,			//Too many references: cannot splice
	ETAT_ETIMEDOUT = -108,				//Connection timed out
	ETAT_ECONNREFUSED = -109,			//Connection refused
	ETAT_EHOSTDOWN = -110,				//Host is down
	ETAT_EHOSTUNREACH = -111,			//No route to host
	ETAT_EALREADY = -112,				//Operation already in progress
	ETAT_EINPROGRESS = -113,			//Operation now in progress
	ETAT_ESTALE = -114,				//Stale NFS file handle
	ETAT_EUCLEAN = -115,				//Structure needs cleaning
	ETAT_ENOTNAM = -116,				//Not a XENIX named type file
	ETAT_ENAVAIL = -117,				//No XENIX semaphores available
	ETAT_EISNAM = -118,				//Is a named type file
	ETAT_EREMOTEIO = -119,				//Remote I/O error
	ETAT_EDQUOT = -120,				//Quota exceeded
	ETAT_ENOMEDIUM = -121,				//No medium found
	ETAT_EMEDIUMTYPE = -122,			//Wrong medium type
	ETAT_ECANCELED = -123,				//Operation Canceled
	ETAT_ENOKEY = -124,				//Required key not available
	ETAT_EKEYEXPIRED = -125,			//Key has expired
	ETAT_EKEYREVOKED = -126,			//Key has been revoked
	ETAT_EKEYREJECTED = -127,			//Key was rejected by service
	ETAT_EOWNERDEAD = -128,			//Owner died
	ETAT_ENOTRECOVERABLE = -129,	//State not recoverable
	ETAT_EBADF = -130,			//Bad file number
} ETAT;

#endif
